services:
  exif-photo-blog:
    image: exif-photo-blog
    ports:
      - "3000:3000"
    depends_on:
      - epb-postgres

  epb-postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: photoblog
    ports:
      - '5432:5432'
    volumes:
      - /volumn/postgres-data:/var/lib/postgresql/data
