services:
  exif-photo-blog:
    image: exif-photo-blog
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - epb-postgres

  epb-postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
